export const serviceLocationsData = [
  // Gujarat Cities & Districts
  { cityName: 'Surat', state: 'Gujarat', region: 'GUJARAT', isHub: true, coordinates: { lat: 21.1702, lng: 72.8311 } },
  { cityName: 'Ahmedabad', state: 'Gujarat', region: 'GUJARAT', isHub: true, coordinates: { lat: 23.0225, lng: 72.5714 } },
  { cityName: 'Vadodara', state: 'Gujarat', region: 'GUJARAT', isHub: true, coordinates: { lat: 22.3072, lng: 73.1812 } },
  { cityName: 'Rajkot', state: 'Gujarat', region: 'GUJARAT', isHub: true, coordinates: { lat: 22.3039, lng: 70.8022 } },
  { cityName: 'Gandhinagar', state: 'Gujarat', region: 'GUJARAT', isHub: false, coordinates: { lat: 23.2156, lng: 72.6369 } },
  { cityName: 'Bhavnagar', state: 'Gujarat', region: 'GUJARAT', isHub: false, coordinates: { lat: 21.7645, lng: 72.1519 } },
  { cityName: 'Jamnagar', state: 'Gujarat', region: 'GUJARAT', isHub: false, coordinates: { lat: 22.4707, lng: 70.0577 } },
  { cityName: 'Junagadh', state: 'Gujarat', region: 'GUJARAT', isHub: false, coordinates: { lat: 21.5222, lng: 70.4579 } },
  { cityName: 'Anand', state: 'Gujarat', region: 'GUJARAT', isHub: false, coordinates: { lat: 22.5645, lng: 72.9289 } },
  { cityName: 'Bharuch', state: 'Gujarat', region: 'GUJARAT', isHub: true, coordinates: { lat: 21.7051, lng: 72.9959 } },
  { cityName: 'Vapi', state: 'Gujarat', region: 'GUJARAT', isHub: true, coordinates: { lat: 20.3893, lng: 72.9106 } },
  { cityName: 'Valsad', state: 'Gujarat', region: 'GUJARAT', isHub: false, coordinates: { lat: 20.5992, lng: 72.9342 } },
  { cityName: 'Mehsana', state: 'Gujarat', region: 'GUJARAT', isHub: false, coordinates: { lat: 23.5880, lng: 72.3693 } },
  { cityName: 'Morbi', state: 'Gujarat', region: 'GUJARAT', isHub: true, coordinates: { lat: 22.8173, lng: 70.8372 } },
  { cityName: 'Navsari', state: 'Gujarat', region: 'GUJARAT', isHub: false, coordinates: { lat: 20.9500, lng: 72.9300 } },
  { cityName: 'Nadiad', state: 'Gujarat', region: 'GUJARAT', isHub: false, coordinates: { lat: 22.6916, lng: 72.8634 } },
  { cityName: 'Palanpur', state: 'Gujarat', region: 'GUJARAT', isHub: false, coordinates: { lat: 24.1724, lng: 72.4346 } },
  { cityName: 'Porbandar', state: 'Gujarat', region: 'GUJARAT', isHub: false, coordinates: { lat: 21.6417, lng: 69.6293 } },
  { cityName: 'Gandhidham', state: 'Gujarat', region: 'GUJARAT', isHub: true, coordinates: { lat: 23.0753, lng: 70.1337 } },
  { cityName: 'Bhuj', state: 'Gujarat', region: 'GUJARAT', isHub: false, coordinates: { lat: 23.2420, lng: 69.6669 } },

  // Rest of Major Indian Cities
  { cityName: 'Mumbai', state: 'Maharashtra', region: 'REST_OF_INDIA', isHub: true, coordinates: { lat: 19.0760, lng: 72.8777 } },
  { cityName: 'Delhi', state: 'Delhi', region: 'REST_OF_INDIA', isHub: true, coordinates: { lat: 28.7041, lng: 77.1025 } },
  { cityName: 'Bengaluru', state: 'Karnataka', region: 'REST_OF_INDIA', isHub: true, coordinates: { lat: 12.9716, lng: 77.5946 } },
  { cityName: 'Hyderabad', state: 'Telangana', region: 'REST_OF_INDIA', isHub: true, coordinates: { lat: 17.3850, lng: 78.4867 } },
  { cityName: 'Chennai', state: 'Tamil Nadu', region: 'REST_OF_INDIA', isHub: true, coordinates: { lat: 13.0827, lng: 80.2707 } },
  { cityName: 'Kolkata', state: 'West Bengal', region: 'REST_OF_INDIA', isHub: true, coordinates: { lat: 22.5726, lng: 88.3639 } },
  { cityName: 'Pune', state: 'Maharashtra', region: 'REST_OF_INDIA', isHub: true, coordinates: { lat: 18.5204, lng: 73.8567 } }
];

export const demoDriversData = [
  {
    name: 'Rahul Patel',
    email: 'rahul.driver@trucklink.com',
    mobile: '9876543210',
    baseCity: 'Surat',
    experienceYears: 6,
    truckNumber: 'GJ-05-AB-1234',
    registrationNumber: 'IND-981245',
    truckType: 'Medium Truck',
    capacityTons: 15,
    preferredRoutes: ['Surat - Mumbai', 'Surat - Vadodara', 'Surat - Ahmedabad'],
    materialTypesAccepted: ['Textiles', 'General Cargo', 'Yarn & Fabric'],
    availabilityStatus: 'AVAILABLE',
    originCity: 'Surat',
    destinationCity: 'Mumbai',
    maxWeightTons: 15,
    materialType: 'Textiles',
    rating: 4.9,
    totalReviews: 24,
    completedDeliveries: 38
  },
  {
    name: 'Amit Shah',
    email: 'amit.driver@trucklink.com',
    mobile: '9876543211',
    baseCity: 'Ahmedabad',
    experienceYears: 8,
    truckNumber: 'GJ-01-CD-5678',
    registrationNumber: 'IND-981246',
    truckType: 'Heavy Truck',
    capacityTons: 25,
    preferredRoutes: ['Ahmedabad - Mumbai', 'Ahmedabad - Delhi', 'Ahmedabad - Pune'],
    materialTypesAccepted: ['Industrial Machinery', 'Steel Rods', 'Chemical Containers'],
    availabilityStatus: 'AVAILABLE',
    originCity: 'Ahmedabad',
    destinationCity: 'Vadodara',
    maxWeightTons: 22,
    materialType: 'Industrial Machinery',
    rating: 4.8,
    totalReviews: 31,
    completedDeliveries: 45
  },
  {
    name: 'Vijay Parmar',
    email: 'vijay.driver@trucklink.com',
    mobile: '9876543212',
    baseCity: 'Vadodara',
    experienceYears: 5,
    truckNumber: 'GJ-06-EF-9012',
    registrationNumber: 'IND-981247',
    truckType: 'Light Commercial Vehicle',
    capacityTons: 7,
    preferredRoutes: ['Vadodara - Surat', 'Vadodara - Anand', 'Vadodara - Ahmedabad'],
    materialTypesAccepted: ['FMCG Goods', 'Pharmaceuticals', 'Electronics'],
    availabilityStatus: 'AVAILABLE',
    originCity: 'Vadodara',
    destinationCity: 'Surat',
    maxWeightTons: 6.5,
    materialType: 'FMCG Goods',
    rating: 4.7,
    totalReviews: 18,
    completedDeliveries: 29
  },
  {
    name: 'Karan Solanki',
    email: 'karan.driver@trucklink.com',
    mobile: '9876543213',
    baseCity: 'Rajkot',
    experienceYears: 10,
    truckNumber: 'GJ-03-GH-3456',
    registrationNumber: 'IND-981248',
    truckType: 'Trailer',
    capacityTons: 35,
    preferredRoutes: ['Rajkot - Ahmedabad', 'Morbi - Mumbai', 'Gandhidham - Delhi'],
    materialTypesAccepted: ['Ceramic Tiles', 'Heavy Cables', 'Automobile Parts'],
    availabilityStatus: 'AVAILABLE',
    originCity: 'Morbi',
    destinationCity: 'Mumbai',
    maxWeightTons: 30,
    materialType: 'Ceramic Tiles',
    rating: 4.9,
    totalReviews: 42,
    completedDeliveries: 67
  },
  {
    name: 'Rajesh Kumar',
    email: 'rajesh.driver@trucklink.com',
    mobile: '9876543214',
    baseCity: 'Vapi',
    experienceYears: 4,
    truckNumber: 'GJ-15-JK-7890',
    registrationNumber: 'IND-981249',
    truckType: 'Medium Truck',
    capacityTons: 12,
    preferredRoutes: ['Vapi - Mumbai', 'Vapi - Surat', 'Vapi - Pune'],
    materialTypesAccepted: ['Plastics', 'Chemical Drums', 'Packaging Material'],
    availabilityStatus: 'AVAILABLE',
    originCity: 'Vapi',
    destinationCity: 'Mumbai',
    maxWeightTons: 11,
    materialType: 'Plastics',
    rating: 4.6,
    totalReviews: 15,
    completedDeliveries: 22
  },
  {
    name: 'Suresh Joshi',
    email: 'suresh.driver@trucklink.com',
    mobile: '9876543215',
    baseCity: 'Gandhidham',
    experienceYears: 9,
    truckNumber: 'GJ-12-LM-1122',
    registrationNumber: 'IND-981250',
    truckType: 'Heavy Truck',
    capacityTons: 28,
    preferredRoutes: ['Gandhidham - Ahmedabad', 'Bhuj - Delhi', 'Kandla - Mumbai'],
    materialTypesAccepted: ['Port Cargo', 'Salt Bags', 'Mineral Ores'],
    availabilityStatus: 'AVAILABLE',
    originCity: 'Gandhidham',
    destinationCity: 'Ahmedabad',
    maxWeightTons: 25,
    materialType: 'Port Cargo',
    rating: 4.85,
    totalReviews: 29,
    completedDeliveries: 51
  },
  {
    name: 'Vikram Singh',
    email: 'vikram.driver@trucklink.com',
    mobile: '9876543216',
    baseCity: 'Bharuch',
    experienceYears: 7,
    truckNumber: 'GJ-16-NP-3344',
    registrationNumber: 'IND-981251',
    truckType: 'Medium Truck',
    capacityTons: 16,
    preferredRoutes: ['Bharuch - Surat', 'Bharuch - Vadodara', 'Ankleshwar - Mumbai'],
    materialTypesAccepted: ['Petrochemicals', 'Dyes & Intermediates', 'Fertilizers'],
    availabilityStatus: 'AVAILABLE',
    originCity: 'Bharuch',
    destinationCity: 'Vadodara',
    maxWeightTons: 14,
    materialType: 'Petrochemicals',
    rating: 4.75,
    totalReviews: 21,
    completedDeliveries: 34
  },
  {
    name: 'Hardik Thakar',
    email: 'hardik.driver@trucklink.com',
    mobile: '9876543217',
    baseCity: 'Anand',
    experienceYears: 3,
    truckNumber: 'GJ-23-QR-5566',
    registrationNumber: 'IND-981252',
    truckType: 'Mini Truck',
    capacityTons: 4,
    preferredRoutes: ['Anand - Vadodara', 'Anand - Nadiad', 'Anand - Ahmedabad'],
    materialTypesAccepted: ['Dairy Products', 'Agricultural Produce', 'Food Items'],
    availabilityStatus: 'AVAILABLE',
    originCity: 'Anand',
    destinationCity: 'Vadodara',
    maxWeightTons: 3.5,
    materialType: 'Dairy Products',
    rating: 4.95,
    totalReviews: 12,
    completedDeliveries: 19
  },
  {
    name: 'Deepak Varma',
    email: 'deepak.driver@trucklink.com',
    mobile: '9876543218',
    baseCity: 'Mumbai',
    experienceYears: 11,
    truckNumber: 'MH-04-ST-7788',
    registrationNumber: 'IND-981253',
    truckType: 'Heavy Truck',
    capacityTons: 20,
    preferredRoutes: ['Mumbai - Surat', 'Mumbai - Pune', 'Mumbai - Ahmedabad'],
    materialTypesAccepted: ['Imported Goods', 'Auto Spares', 'Consumer Goods'],
    availabilityStatus: 'AVAILABLE',
    originCity: 'Mumbai',
    destinationCity: 'Surat',
    maxWeightTons: 18,
    materialType: 'Imported Goods',
    rating: 4.8,
    totalReviews: 38,
    completedDeliveries: 74
  },
  {
    name: 'Manthan Rana',
    email: 'manthan.driver@trucklink.com',
    mobile: '9876543219',
    baseCity: 'Morbi',
    experienceYears: 6,
    truckNumber: 'GJ-36-UV-9900',
    registrationNumber: 'IND-981254',
    truckType: 'Medium Truck',
    capacityTons: 14,
    preferredRoutes: ['Morbi - Rajkot', 'Morbi - Ahmedabad', 'Morbi - Surat'],
    materialTypesAccepted: ['Sanitaryware', 'Ceramic Tiles', 'Building Materials'],
    availabilityStatus: 'AVAILABLE',
    originCity: 'Morbi',
    destinationCity: 'Ahmedabad',
    maxWeightTons: 13,
    materialType: 'Sanitaryware',
    rating: 4.7,
    totalReviews: 16,
    completedDeliveries: 27
  }
];

export const demoCompaniesData = [
  {
    name: 'Rajesh Shah',
    email: 'contact@abctextiles.com',
    mobile: '9988776655',
    companyName: 'ABC Textiles Pvt Ltd',
    contactPerson: 'Rajesh Shah',
    businessType: 'Manufacturer',
    gstNumber: '24AAACA1234A1Z5',
    companyAddress: 'Plot 42, Ring Road Textile Market',
    city: 'Surat',
    state: 'Gujarat'
  },
  {
    name: 'Mehul Patel',
    email: 'logistics@gujaratmfg.com',
    mobile: '9988776656',
    companyName: 'Gujarat Manufacturing Corp',
    contactPerson: 'Mehul Patel',
    businessType: 'Manufacturer',
    gstNumber: '24BBBCB5678B1Z2',
    companyAddress: 'GIDC Industrial Estate Phase 2',
    city: 'Vadodara',
    state: 'Gujarat'
  },
  {
    name: 'Sneha Roy',
    email: 'orders@westernfoods.in',
    mobile: '9988776657',
    companyName: 'Western Foods & Beverages',
    contactPerson: 'Sneha Roy',
    businessType: 'Distributor',
    gstNumber: '24CCCC19012C1Z9',
    companyAddress: 'SG Highway Commercial Hub',
    city: 'Ahmedabad',
    state: 'Gujarat'
  },
  {
    name: 'Pankaj Mehta',
    email: 'supply@urbanretail.com',
    mobile: '9988776658',
    companyName: 'Urban Retail India',
    contactPerson: 'Pankaj Mehta',
    businessType: 'Retailer',
    gstNumber: '27DDDDD3456D1Z4',
    companyAddress: 'Lower Parel Commercial Complex',
    city: 'Mumbai',
    state: 'Maharashtra'
  },
  {
    name: 'Kirit Ceramic',
    email: 'dispatch@morbiceramics.com',
    mobile: '9988776659',
    companyName: 'Vibrant Ceramics & Tiles',
    contactPerson: 'Kirit Ceramic',
    businessType: 'Wholesaler',
    gstNumber: '24EEEEE7890E1Z1',
    companyAddress: 'Navlakhi Road Ceramic Zone',
    city: 'Morbi',
    state: 'Gujarat'
  }
];
